private_message_nodejs.settings:
  type: config_object
  label: 'Settings for the Private Message Nodejs module'
  mapping:
    enable_debug:
      type: boolean
      label: 'Whether or not module debugging should be enabled'
    nodejs_url:
      type: string
      label: 'The URL at which the Nodejs server can be reached'
    nodejs_secret:
      type: string
      label: 'Node.js secret - an arbitrary key used for security of communication'
    browser_notification_enable:
      type: boolean
      label: 'Whether or not to enable browser notifications'
    browser_notification_title:
      type: string
      label: 'The title to be shown in the browser notification'
    browser_notification_body:
      type: string
      label: 'The body of the browser notification'
    browser_notification_icon:
      type: string
      label: 'The path to the icon to be used in browser notifictions'
    browser_notification_link:
      type: string
      label: 'The URL users will be directed to when clicking a browser notification'
