chatroom.settings:
  type: config_object
  label: 'Chatroom settings'
  mapping:
    msg_date_format:
      type: string
      label: 'Message date format'
    command_prefix:
      type: string
      label: 'Command prefix'
    allow_anon_name:
      type: boolean
      label: 'Allow anonymous name'

